development:
  host: doc.engine.dev
  email: did@nocoffee.fr
  password: test31
staging:
  host: staging.example.com
  email: john@doe.net
  password: easyone
production:
  host: locomotivedummy.herokuapp.com
  email: didier@nocoffee.fr
  password: test31
