site:
  name: Documentation

  locales: [en]

  seo_title: LocomotiveCMS - Documentation
  meta_keywords: "some meta keywords"
  meta_description: "some meta description"

  pages:
    - index:
        title: "Home page"
        published: true
    - 404:
        title: "Page not found"
        published: true
    - installation:
        title: "Installation"
        published: true
    - installation/for_developpers:
        title: "For developpers"
        published: true
    - installation/getting_started:
        title: "Getting started"
        published: true
    - installation/heroku_hosting:
        title: "Heroku hosting"
        published: true
    - installation/requirements:
        title: "Requirements"
        published: true
    - guides:
        title: "Guides"
        published: true
    - guide/pat-1:
        published: true
    - guide/pat-2:
        published: true
    - guide/pat-3:
        published: true
    - guide/pat-4:
        published: true